### PR TITLE
improved error messages

### PR DESCRIPTION
**Pull request by oharboe**
use run_quietly() for those cases where there should be no output on success, but if there was an error, a full dump of stdout and stderr should be done

### CODE REVIEW

**Comment by mithro** [comment]
I think this looks okay, go an example of before / after to take a quick look at?

**Comment by oharboe** [comment]
> I think this looks okay, go an example of before / after to take a quick look at?

Yes, that is reasonable, buy tricky. Three code paths so  six runs minimum :-)

BTW are these config options tested in CI?

If not, could they be or is there a technical or reason otherwise not to?

**Comment by mithro** [comment]
I was only after a quick single example as a quick spot check -- no need to provide them all.

These options **_should_** be tested on CI, no idea if they are or not.

**Comment by oharboe** [comment]
> I was only after a quick single example as a quick spot check -- no need to provide them all.
> 
> These options **_should_** be tested on CI, no idea if they are or not.

There is no rush on my part. I am more interested in robust testing of this than a quick fix. Good error messages on yosys is critical for usability of this plugin as most user errors are likely to be in yosys input....

**Comment by mithro** [comment]
As the person doing the work, I'm happy to follow your lead here.

**Comment by oharboe** [comment]
This code-path is tested here: https://github.com/SymbiFlow/sphinxcontrib-hdl-diagrams/blob/d06efbf990d7815cfbcfd15967e5a2f66167dbe9/tests/test.py#L101

Here is the after fix output, search for `TEST CASE: TestYowasp`. There are three such tests, only two are changed.

https://pipelines.actions.githubusercontent.com/nh2yGm0h8ax1Y5IzZBWPFwIoV3HAPbMMeWKPYMDTZbOo4I0edd/_apis/pipelines/1/runs/66/signedlogcontent/2?urlExpires=2023-09-25T19%3A53%3A10.0334634Z&urlSigningMethod=HMACV1&urlSignature=fNRPv3NRo9kXXTxnzuIO86098uz3YhEnKP1IXaVeoUs%3D

Pick some random "before" build:

https://github.com/SymbiFlow/sphinxcontrib-hdl-diagrams/actions/runs/6285654790/job/17068261372

Search for `TEST CASE: TestYowasp`

**Comment by mithro** [comment]
I'm going to go ahead and merge.

**Comment by oharboe** [comment]
> I'm going to go ahead and merge.

Thanks! I will be spelunking a bit in the automated tests to see how they work and if there is anything to improve..m

**Pull request merged**
