### PR TITLE
Update README information

### LINKED ISSUE #24: Add a clearer link to the readthedocs documentation
Currently the only link to the readthedocs documentation / examples is the tiny little docs badge 
(image).

We should make a lot more prominent / clear link.

### PR DESCRIPTION
**Pull request by daniellimws**
* Fix all broken badge urls
* Add link to docs at the start of README

Close #24 

Signed-off-by: Daniel Lim Wee Soong <weesoong.lim@gmail.com>

### CODE REVIEW

**Comment by daniellimws** [comment]
Should we update the `conda XXXX` with more information? I'm not sure what to change it to though.

image

**Comment by mithro** [comment]
Hi,

Thank you for sending the pull request! It's awesome to see you contributing to this project. However, before I can look at this request you need to add [DCO sign-off](https://developercertificate.org/) to commits in this repository.

We require [DCO sign-off](https://developercertificate.org/) for **all** commits to this repository (including all authors). Please see the [following URL](https://github.com/probot/dco#how-it-works) to see more information and BeeWare also have a [Beginners guide to DCOs](https://pybee.org/contributing/how/dco/).

You can use `git commit --amend --signoff` and then a `git push --force` to add the signoff. You can also use `git rebase --signoff`.

Thanks!

**Comment by mithro** [comment]
> Should we update the `conda XXXX` with more information? I'm not sure what to change it to though.
> 
> image

Yes, let's add this!

See example at https://github.com/SymbiFlow/symbiflow-examples ?

**Comment by mithro** [comment]
This look good! Can you rebase onto master?

**Comment by daniellimws** [comment]
@mithro Ok rebased

**Pull request merged**
